{% set name = "scikit-criteria" %}
{% set version = "0.8.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scikit-criteria-{{ version }}.tar.gz
  sha256: d3cda3103ba8030409de8804ddcfceba596faf4897cc4798766d6d171e0437d9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - numpy
    - pandas
    - pyquery
    - scipy
    - jinja2
    - custom-inherit
    - seaborn
    - deprecated
    - pulp
    - scikit-learn
    - importlib_metadata
    - matplotlib-base !=3.6.1

test:
  imports:
    - skcriteria
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://scikit-criteria.org/
  summary: |
    Scikit-Criteria is a collection of Multiple-criteria decision analysis (MCDA) methods integrated into scientific python stack. Is Open source and commercially usable.
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - hadim
