{% set name = "scikit-criteria" %}
{% set version = "0.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scikit-criteria-{{ version }}.tar.gz
  sha256: 98f41c3c0e8808eea0e473cd97bf6f835a42578756cc9b68d06baa6bff92b0f2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - numpy
    - pandas
    - pyquery
    - scipy
    - jinja2
    - custom-inherit
    - seaborn
    - pulp
    - deprecated

test:
  imports:
    - skcriteria
  commands:
    - pip check
  requires:
    - pip
#     - mock  # for `pip check`
#     - pytest  # for `pip check`

about:
  home: http://scikit-criteria.org/
  summary: |
    Scikit-Criteria is a collection of Multiple-criteria decision analysis (MCDA) methods integrated into scientific python stack. Is Open source and commercially usable.
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - hadim
