{% set name = "scikit-criteria" %}
{% set version = "0.8.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/scikit-criteria-{{ version }}.tar.gz
  sha256: 2c55c2fca23e61a7ded6d17470224e73d6c590b57da98b9d1e9f4411a9873221

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - numpy
    - pandas
    - pyquery
    - scipy
    - jinja2
    - custom-inherit
    - seaborn
    - deprecated
    - pulp
    - scikit-learn
    - importlib_metadata
    - matplotlib-base >=3.8.2
    - methodtools

test:
  requires:
    - python {{ python_min }}
  imports:
    - skcriteria

about:
  home: http://scikit-criteria.org/
  summary: |
    Scikit-Criteria is a collection of Multiple-criteria decision analysis (MCDA) methods integrated into scientific python stack. Is Open source and commercially usable.
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - hadim
