context:
  name: scikit-criteria
  version: "0.9"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 6a463258f26b389fda370d20bb4521191579b2486d8d9b472aeddfda12c4ebfe

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}
    - numpy >=2.0
    - networkx >=3.2
    - pandas >=2.0
    - scipy >=1.10
    - jinja2
    - custom_inherit
    - seaborn >=0.13,<0.14
    - pulp >=2.8,<2.9
    - deprecated
    - scikit-learn >=1.6
    - matplotlib-base >=3.8.2,<3.9
    - methodtools
    - pyyaml >=6.0

tests:
  - python:
      imports:
        - skcriteria
      python_version: ${{ python_min }}.*

about:
  summary: |
    Scikit-Criteria is a collection of Multiple-criteria decision analysis (MCDA) methods integrated into scientific python stack. Is Open source and commercially usable.
  license: BSD-3-Clause
  license_file: LICENSE.txt
  homepage: https://github.com/quatrope/scikit-criteria

extra:
  recipe-maintainers:
    - hadim
